class BaseUrl{
  static String login = 'https://flutplantshop.000webhostapp.com/api/login.php';
  static String register = 'https://flutplantshop.000webhostapp.com/api/register.php';
  static String product = 'https://flutplantshop.000webhostapp.com/api/product.php';
  static String lihatProduk = 'https://flutplantshop.000webhostapp.com/api/lihatProduk.php';
  static String editProduk = 'https://flutplantshop.000webhostapp.com/api/editproduk.php';
  static String editalamat = 'https://flutplantshop.000webhostapp.com/api/editalamat.php';
  static String editjumlah = 'https://flutplantshop.000webhostapp.com/api/editjumlah.php';
  static String deleteProduk = 'https://flutplantshop.000webhostapp.com/api/deleteproduk.php';
  static String deletealamat = 'https://flutplantshop.000webhostapp.com/api/deletealamat.php';
  static String tambahKeranjang = 'https://flutplantshop.000webhostapp.com/api/tambahKeranjang.php';
  static String jumlahKeranjang = 'https://flutplantshop.000webhostapp.com/api/lihatKeranjang.php?idUsers=';
  static String totalharga = 'https://flutplantshop.000webhostapp.com/api/totalharga.php?idUsers=';
  static String lihatProdukIndoor = 'https://flutplantshop.000webhostapp.com/api/lihatProdukIndoor.php';
  static String lihatProdukOutdoor = 'https://flutplantshop.000webhostapp.com/api/lihatProdukOutdoor.php';
  static String lihatProdukAksesoris = 'https://flutplantshop.000webhostapp.com/api/lihatProdukAksesoris.php';
  static String lihatAlamatAdmin = 'https://flutplantshop.000webhostapp.com/api/lihatalamatadmin.php';
  static String lihatAlamat = 'https://flutplantshop.000webhostapp.com/api/lihatalamat.php?idUsers=';
  static String lihatKeranjangdata = 'https://flutplantshop.000webhostapp.com/api/lihatKeranjangdata.php?idUsers=';
  static String lihatKonfirmasiKeranjang = 'https://flutplantshop.000webhostapp.com/api/lihatKonfirmasikeranjang.php?idUsers=';
  static String lihatkonfirmasikeranjangadmincod = 'https://flutplantshop.000webhostapp.com/api/lihatkonfirmasikeranjangadmincod.php';
  static String lihatkonfirmasikeranjangadmintf = 'https://flutplantshop.000webhostapp.com/api/lihatkonfirmasikeranjangadmintf.php';
  static String deleteProdukKeranjang = 'https://flutplantshop.000webhostapp.com/api/deleteprodukkeranjang.php';
  static String refreshkeranjang = 'https://flutplantshop.000webhostapp.com/api/refreshkeranjang.php';
  static String deleteverifyproduk = 'https://flutplantshop.000webhostapp.com/api/deleteverifykeranjang.php';
  static String favorite = 'https://flutplantshop.000webhostapp.com/api/favorite.php';
  static String deletefavorite = 'https://flutplantshop.000webhostapp.com/api/deletefavorite.php';
  static String deletebukti = 'https://flutplantshop.000webhostapp.com/api/deletebukti.php';
  static String deletecod = 'https://flutplantshop.000webhostapp.com/api/deletecod.php';
  static String lihatFavoritedata ='https://flutplantshop.000webhostapp.com/api/lihatFavoritedata.php';
  static String alamat = 'https://flutplantshop.000webhostapp.com/api/alamat.php';
  static String bukti = 'https://flutplantshop.000webhostapp.com/api/bukti.php';
  static String cod = 'https://flutplantshop.000webhostapp.com/api/cod.php';
  static String productVerifycod = 'https://flutplantshop.000webhostapp.com/api/productverifycod.php';
  static String productVerifytf = 'https://flutplantshop.000webhostapp.com/api/productverifytransfer.php';
  static String lihatbukti = 'https://flutplantshop.000webhostapp.com/api/LihatBuktiData.php?idUsers=';
  static String lihatcod = 'https://flutplantshop.000webhostapp.com/api/lihatcod.php?idUsers=';
  static String lihatbuktiadmin = 'https://flutplantshop.000webhostapp.com/api/lihatbuktiadmin.php';
  static String lihatcodadmin = 'https://flutplantshop.000webhostapp.com/api/lihatcodadmin.php';
  static String updateverifikasi ='https://flutplantshop.000webhostapp.com/api/updateverifikasi.php';
  static String updatecod ='https://flutplantshop.000webhostapp.com/api/updateverifikasicod.php';
}