/// Flutter icons Aksesoris
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Aksesoris
///      fonts:
///       - asset: fonts/Aksesoris.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Aksesoris {
  Aksesoris._();

  static const _kFontFam = 'Aksesoris';

  static const IconData watering =
      const IconData(0xe800, fontFamily: _kFontFam);
}
