/// Flutter icons Pohon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pohon
///      fonts:
///       - asset: fonts/Pohon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Pohon {
  Pohon._();

  static const _kFontFam = 'Pohon';

  static const IconData pohon = const IconData(0xe800, fontFamily: _kFontFam);
}
