/// Flutter icons Siram
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Siram
///      fonts:
///       - asset: fonts/Siram.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Siram {
  Siram._();

  static const _kFontFam = 'Siram';

  static const IconData siram = const IconData(0xe800, fontFamily: _kFontFam);
}
